Undertimes
HollishKid/Gaia pull request #117
Opened 2017-08-13 13:47 UTC by Undertimes

Le pnj et ses quêtes journalières sont prêtes! Les différentes quêtes fonctionnent (tests réussis sur le serveur dev) et le pnj se débloque pour les joueurs ayant atteint le grade d'écuyer.

2017-08-13 16:17 UTC, crashoz requested changes
C'est tout bon, je met juste en attente jusqu'à ce qu'on ait les pnj de placés sur le prod

2017-08-13 16:17 UTC, crashoz commented on BetonQuest/Undertimes/Quêtes Sanctuaire/main.yml
> +npcs:
Mettre des id de pnj recyclés sur le prod et les placer aux endroits adéquats

2017-08-15 13:13 UTC, HollishKid commented
Ce PR m'a l'air très bien, mais je me pose quelques questions.
- n'y a-t-il pas un niveau de dossiers en trop ? UnderTimes > Quêtes sanctuaire
Il me semble que c'est théoriquement possible, je me pose plutôt des questions de "facilité" ;
- ne va-t-il pas y avoir de souci dans la définition des tags, objectifs etc. avec un espace et un caractère spécial dans un nom de package ?
On aurait du UnderTimes.Quêtes Sancutaire.nom_du_tag ; ce qui me parait pas optimal ?
- a plus long terme on n'aurait-t-on pas du mal à faire référence à ce package ?
- une fois en place on ne peut pas le modifier, puisque les joueur auront déjà des tags etc. du format que j'ai donné plus haut.

2017-08-15 13:18 UTC, crashoz commented
Effectivement je n'avais pas vu, ce serait bien mieux d'avoir les quêtes dans un seul dossier UnderTimes je suis d'accord.

2017-08-20 14:45 UTC, Undertimes commented
En effet, il serai plus efficace de ne pas avoir de sous dossier, sous tout les angles. 

Un autre détail que j'ai oublié de préciser est que le pnj 'joseph' situé dans le château royal peut être merge avec un autre pnj lié au sanctuaire, par exemple l'un des pnj du second étage, étant donné que ces quêtes ne sont accessibles qu'aux écuyers. Si vous avez une idée, n'hésitez pas. 

_Sent from my Sony D5803 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

2017-08-22 10:18 UTC, Undertimes commented
Le sous-dossier est supprimé, y a-t-il autre chose à modifier?

2017-08-23 23:41 UTC, HollishKid submitted a review, later dismissed

2017-08-23 23:41 UTC, HollishKid commented on BetonQuest/Undertimes/Quêtes Sanctuaire/conversations/gardien_sanctuaire.yml
> +    text: 'Bien. Quelle difficulté voulez-vous?'
Je vais faire le pointilleux sur la ponctuation, comme ça ce sera fait maintenant, plutôt que de corriger par PR séparé.

- Les ponctuations "doubles" ( : ; ! ?) sont toujours précédés d'un espace.
- Les ponctuations "simples" ( . , ...) ne le sont jamais.

2017-08-23 23:41 UTC, HollishKid commented on BetonQuest/Undertimes/Quêtes Sanctuaire/conversations/gardien_sanctuaire.yml
> +    text: 'Apportez ce paquet au Chateau royal.'
Chateau => Château

2017-08-23 23:41 UTC, HollishKid commented on BetonQuest/Undertimes/Quêtes Sanctuaire/items.yml
> +josephpackage: 'CHEST name:&2Colis_du_Sanctuaire lore:A_livrer_à_Joseph_au_Chateau!'
Peut être faudrait-il faire un quest item de cet objet ? (se range dans le /sac et ne peux jamais être perdu, sauf si repris par BQ)

Pour ce faire, il faudrait :
lore:A_livrer_à_Joseph_au_Château_!;§2Objet_de_Quête'

2017-08-23 23:41 UTC, HollishKid commented on BetonQuest/Undertimes/Quêtes Sanctuaire/items.yml
> +questbone: 'BONE name:&2Os_mystique lore:Dans_votre_main,_il_en_émane_une_force_étrange.'
lore:Dans_votre_main;il_en_émane_une_force_étrange.

Un peu long sur une seule ligne de lore sinon, non ?

2017-08-23 23:49 UTC, HollishKid requested changes

2017-08-23 23:49 UTC, HollishKid commented on BetonQuest/Undertimes/conversations/gardien_sanctuaire.yml
> +    text: 'Bien. Quelle difficulté voulez-vous?'
Cette fois dans le bon emplacement.

Je vais faire le pointilleux sur la ponctuation.
Pour toute double ponctuation ( : ; ! ? ) il faut le faire précéder d'un espace.
(Pour ne pas spammer, je le relève à les première occurrence, mais y'en a quelques un dans tes conversations & events.)

2017-08-23 23:49 UTC, HollishKid commented on BetonQuest/Undertimes/conversations/gardien_sanctuaire.yml
> +    text: 'Apportez ce paquet au Chateau royal.'
Château au lieu de Chateau

2017-08-23 23:49 UTC, HollishKid commented on BetonQuest/Undertimes/items.yml
> +josephpackage: 'CHEST name:&2Colis_du_Sanctuaire lore:A_livrer_à_Joseph_au_Chateau!'
Peut être serait-ce une idée de faire un objet de quête ? (ne se perd jamais et peut être rangé dans le /sac)

Il faudrait alors :
josephpackage: 'CHEST name:&2Colis_du_Sanctuaire lore:A_livrer_à_Joseph_au_Château_!;§2Objet_de_Quête'

2017-08-23 23:49 UTC, HollishKid commented on BetonQuest/Undertimes/items.yml
> +questbone: 'BONE name:&2Os_mystique lore:Dans_votre_main,_il_en_émane_une_force_étrange.'
La seule ligne de lore semble un peu chargée. Et si tu divisais en deux lignes ?

questbone: 'BONE name:&2Os_mystique lore:Dans_votre_main;il_en_émane_une_force_étrange.'

2017-08-24 10:24 UTC, Undertimes commented
Modifications appliquées, ça devrait être bon pour ce que Hollish a relevé.

2017-08-24 11:23 UTC, HollishKid approved these changes

2017-08-24 11:31 UTC, crashoz approved these changes

2017-08-25 15:56 UTC, HollishKid requested changes

2017-08-25 15:56 UTC, HollishKid commented on MythicMobs/Spawners/pnj_gardien.yml
> +  LeashRange: 50
Tu devrais passer le LeashRange à 1 pour que le PNJ reste bien là ou tu le fais spawner.

2017-08-25 15:56 UTC, HollishKid commented on MythicMobs/Spawners/pnj_joseph.yml
> +  LeashRange: 50
Idem ici, LeashRange: 1

2017-08-25 16:01 UTC, Undertimes commented on MythicMobs/Spawners/pnj_joseph.yml
> +  LeashRange: 50
Ah oui, je pensais l'avoir modifié pourtant... Bah, je m'en occupe tout de suite!

2017-08-26 11:53 UTC, Undertimes commented
Plus que l'approbation de @HollishKid et je merge.

2017-08-26 13:52 UTC, HollishKid approved these changes

2017-08-26 15:49 UTC, merged