Lauvel 1.1
HollishKid/Gaia pull request #47
Opened 2017-03-02 20:32 UTC by Lauvel

Pull request du dossier Lauvel, version 1.1 

Ajoute de nouveaux PNJ, suite quêtes permettant au joueur de visiter la mine et forêt !

2017-03-03 12:34 UTC, crashoz requested changes
Petite incohérence entre l'item BetonQuest et MythicMobs. Il faut que l'item soit **exactement** le même sinon il ne sera pas reconnu correctement par BetonQuest. Sinon très bien 👍

2017-03-03 12:34 UTC, crashoz commented on BetonQuest/lauvel/objectives.yml
> +Cc_4: setblock AIR ???;???;???;Gaia
l'objectif *setblock* n'existe pas à ma connaissance? Ni les locations avec *???*
Ca me semble être une erreur ou alors ce n'est pas fini!

2017-03-03 12:34 UTC, crashoz commented on MythicMobs/Items/Chair_Mute.yml
> +  Display: 'Chair_Muté'
Attention, il faut être cohérent entre MythicMobs et BetonQuest. Ici le nom doit être **'Chair Mutée'** ( sans _ )
(et je crois bien que muté s'accorde avec chair)

2017-03-03 12:34 UTC, crashoz commented on BetonQuest/lauvel/items.yml
> +Chair_Mute: ROTTEN_FLESH data:0 name:Chair_Mute lore:Chair_humaine_d'une_personne_muté;§2Objet_de_Quête
Attention, il faut être cohérent entre MythicMobs et BetonQuest. Ici le nom doit être **Chair_Mutée** ( avec le _ et le é ).

2017-03-03 12:37 UTC, crashoz commented
Je me demande même si ça marche de mettre un item MythicMob dans BetonQuest, qu'en pense @HollishKid ?

2017-03-03 16:57 UTC, HollishKid commented on BetonQuest/lauvel/objectives.yml
> +Cc_4: setblock AIR ???;???;???;Gaia
Non, l' "event" setblock sous ce format existe, mais pas l'objectif.

Si tu veux que le joueur place un bloc le format de l'objectif est le suivant:
obj_buches: block LOG:2 -16 events:reward notify

(négatif pour casser, positif pour placer, ici avec "notify" pour avertir de la progression le joueur).

2017-03-03 17:02 UTC, HollishKid commented
BetonQuest n'est pas expert dans la gestion d'objets en réalité. J'ai fais la demande à Coosh d'améliorer le système, chose qui se fait progressivement.
Il me semble le "unbreakable" a été ajouté, mais qu'on n'a toujours pas la possibilité de mettre des attributs génériques (qui se font très bien avec MythicMobs !) dans BetonQuest, par exemple.

Après, si on s'applique et que les items sont identiques, j'ai déjà testé avec succès un item généré par MM avec une condition BQ.
C'est donc à bien vérifier et tester IG ; mais tu peux le faire marcher =)

2017-03-03 17:25 UTC, Lauvel commented on BetonQuest/lauvel/objectives.yml
> +Cc_4: setblock AIR ???;???;???;Gaia
Ah oui, zut j'ai mis ça dans objective. Et oui ??? c’est normal puisque j'ai toujours pas mes batiment nécessaire à cette quêtes.

2017-03-03 17:25 UTC, Lauvel commented on BetonQuest/lauvel/items.yml
> +Chair_Mute: ROTTEN_FLESH data:0 name:Chair_Mute lore:Chair_humaine_d'une_personne_muté;§2Objet_de_Quête
Ah ok je vais toute suite changer alors ^^

2017-04-10 16:37 UTC, crashoz approved these changes

2017-04-10 16:41 UTC, merged